# Server configurations
server:
  host: "localhost"
  port: ":8080"

# Marvel API configurations
marvelapi:
  publickey : ""
  privatekey: ""

# Redis Config for caching
redis:
  host : "localhost"
  port : ":6379"
