basePath: /
consumes:
- n/a
host: localhost:8080
info:
  contact:
    email: nhriddle@gmail.com
    name: Niel Riddle
    url: http://www.nhriddle.com
  description: |-
    the purpose of this application is to provide an application
    that caches and serves Marvel Characters and their IDs on Marvel's database.
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT
  title: Marvel Characters API
  version: 0.0.1
paths:
  /characters:
    get:
      description: Returns a list of character IDs from the marvel universe
      operationId: getCharacters
      responses:
        "200":
          $ref: '#/responses/idList'
  /characters/{id}:
    get:
      description: Returns details of a Marvel Characters
      operationId: getCharacter
      parameters:
      - description: The character ID of the Marvel hero
        format: int64
        in: path
        name: ID
        required: true
        type: integer
      responses:
        "200":
          $ref: '#/responses/result'
        "404":
          $ref: '#/responses/error'
produces:
- application/json
responses:
  error:
    description: ""
    headers:
      Code:
        type: string
      Message:
        type: string
  idList:
    description: ""
    headers:
      IDList:
        items:
          type: string
        type: array
  result:
    description: ""
    headers:
      description:
        type: string
      id:
        format: int64
        type: integer
      name:
        type: string
schemes:
- http
swagger: "2.0"
